language: ruby
services: mongodb
script: "bundle exec rspec spec"
rvm:
  - 2.5.7
  - 2.6.6
gemfile:
  - Gemfile
env:
  - RAILS_VERSION=3.2 MONGOID_VERSION=3.1
  - RAILS_VERSION=4.2.10 MONGOID_VERSION=4.0
  - RAILS_VERSION=4.2.10 MONGOID_VERSION=5.0
  - RAILS_VERSION=5.0 MONGOID_VERSION=6.1
  - RAILS_VERSION=5.1 MONGOID_VERSION=6.2
  - RAILS_VERSION=5.2 MONGOID_VERSION=6.4
  - RAILS_VERSION=6.0.3 MONGOID_VERSION=7.0.8
  - RAILS_VERSION=6.0.3 MONGOID_VERSION=7.1.2
