language: ruby
services: mongodb
rvm:
  - 2.5.1
  - 2.3.7
gemfile:
  - Gemfile
env:
  - RAILS_VERSION=3.2 MONGOID_VERSION=3.1
  - RAILS_VERSION=4.2 MONGOID_VERSION=4.0
  - RAILS_VERSION=4.2 MONGOID_VERSION=5.0
  - RAILS_VERSION=5.2 MONGOID_VERSION=6.0
services:
  - mongodb
